package main

import (
	"time"

	"github.com/breez/lnd-cert-gen/cert"
)

func main() {
	err := generateCerts()
	if err != nil {
		panic(err)
	}
}

func generateCerts() error {
	println("Generating TLS certificates")

	caBytes, caKeyBytes, err := cert.GenCertPair(
		"lnd autogenerated ca cert", []string{},
		[]string{}, false,
		time.Hour*24*265*5, nil, nil,
	)
	if err != nil {
		return err
	}

	certBytes, keyBytes, err := cert.GenCertPair(
		"lnd autogenerated cert", []string{},
		[]string{}, false,
		time.Hour*24*265*5, caBytes, caKeyBytes,
	)
	if err != nil {
		return err
	}

	err = cert.WriteCertPair(
		"ca.cert", "ca.key", caBytes, caKeyBytes,
	)
	if err != nil {
		return err
	}

	err = cert.WriteCertPair(
		"tls.cert", "tls.key", certBytes, keyBytes,
	)

	println("Done generating TLS certificates")

	return err
}
